### ISSUE TITLE
Staging URL not exists!

### ISSUE THREAD

**Issue by ultrasites** [flyeralarm/reseller-example#4]
Hello, 

i tried to run the reseller example but i get an error:

`'https://staging.flyeralarm.com/de/shop/soap/?wsdl' : failed to load external entity`

The url `https://staging.flyeralarm.com/de/shop/soap/?wsdl` not exists! The url is saved in the config: TestDE.php

Can you help me?

**Comment by flyeralarm-esolutions** [comment]
Hallo ultrasites,
 
External users are locked out of our staging system.
 
To get you going, please contact esolutions@flyeralarm.com,
so we can take a look if an API connection makes sense and which route we can take.
 
Afterwards we would enable your access to the systems.
 
Best Regards,
Your FLYERALARM Team
